Repository Qv2ray/Qv2ray, pull requests merged in 2019-09, with the labels that each got.

#46 Update Qv2ray.desktop
  icons/Qv2ray.desktop
Labels: OS-Linux, Type-Packaging

#52 Improve the icons design
  icons/add_connection_btn.png
  icons/add_connection_btn.svg
  icons/edit_connection_btn.png
  icons/edit_connection_btn.svg
  icons/import_connection_btn.png
  icons/import_connection_btn.svg
  icons/remove_connection_btn.png
  icons/remove_connection_btn.svg
  icons/remove_connection_btn_red.png
  src/w_MainWindow.ui
Labels: From-UI-Design, Good-Issue-Or-Suggestion, OS-AnyOS

#53 New Crowdin translations
  translations/ru-RU.ts
Labels: From-UI-Design

#68 [doc] updated docs
  README.md
  docs/FAQ.md
  docs/ReleaseNotes/2.0/v2.0.0.0.md
  src/main.cpp
Labels: test-build-needed

#73 TRANSLATIONS - DEV BRANCH
  translations/ru-RU.ts
  translations/zh-CN.ts
Labels: From-UI-Design

#83 New Crowdin translations
  translations/zh-CN.ts
Labels: test-build-needed

#82 New Crowdin translations
  translations/zh-CN.ts
Labels: test-build-needed

#84 Added connection statistics.
  .appveyor.yml
  .gitignore
  .travis.yml
  Qv2ray.pro
  README.md
  libs/libcrypto-1_1-x64.dll
  libs/libcrypto-1_1.dll
  libs/libcrypto.lib
  libs/libssl-1_1-x64.dll
  libs/libssl-1_1.dll
  libs/libssl.lib
  libs/lrelease.prf
  src/Qv2rayBase.h
  src/QvConfigUpgrade.cpp
  src/QvCoreConfigOperations.h
  src/QvCoreConfigOperations_Generation.cpp
  src/QvCoreInteractions.cpp
  src/QvCoreInteractions.h
  src/QvUtils.cpp
  src/QvUtils.h
  src/main.cpp
  src/ui/w_ImportConfig.cpp
  src/ui/w_MainWindow.cpp
  src/ui/w_MainWindow.h
  src/ui/w_MainWindow.ui
  src/ui/w_PrefrencesWindow.cpp
  src/ui/w_PrefrencesWindow.h
  src/ui/w_PrefrencesWindow.ui
  src/ui/w_SubscribeEditor.cpp
  src/utils/QJsonObjectInsertMacros.h
  src/utils/QvTinyLog.h
  tools/7z.dll
  tools/7z.exe
  tools/deps_macOS.sh
  tools/grpc_gen.bat
  tools/grpc_gen.sh
  tools/lrelease.prf
  tools/v2ray_api_commands.proto
Labels: From-CoreFeatures, From-UI-Design, From-v2ray-Interaction, OS-AnyOS, Type-Compiling
