Repository Qv2ray/Qv2ray, pull requests merged in 2020-02, with the labels that each got.

#309 Implementation of Automatic AUR Build
  .github/workflows/aur.yml
Labels: AUR

#319 [fix] fixed several memory leaks
  Build.Counter
  src/common/QvHelpers.cpp
  src/common/QvHelpers.hpp
  src/components/pac/QvPACHandler.cpp
  src/components/pac/QvPACHandler.hpp
  src/components/plugins/toolbar/QvToolbar_linux.cpp
  src/core/connection/ConnectionIO.cpp
  src/core/kernel/APIBackend.cpp
  src/core/kernel/KernelInteractions.cpp
  src/main.cpp
  src/ui/nodemodels/InboundNodeModel.hpp
  src/ui/nodemodels/OutboundNodeModel.hpp
  src/ui/nodemodels/RuleNodeModel.hpp
  src/ui/w_ImportConfig.cpp
  src/ui/w_MainWindow.cpp
  src/ui/w_MainWindow.hpp
  src/ui/w_MainWindow_extra.cpp
  src/ui/w_PreferencesWindow.cpp
  translations/en_US.ts
Labels: cleanup

#321 Wip/snap
  Qv2ray.pro
  snap/snapcraft.yaml
Labels: platform/linux, t/packaging

#326 Refactoring QvProxyConfigurator.cpp
  src/components/proxy/QvProxyConfigurator.cpp
Labels: cleanup

#352 Fix The F***ing Old Distributions
  .github/workflows/build-qv2ray.yml
Labels: distribution, platform/linux, t/packaging

#374 fix editor subscription changing data lose
  src/ui/w_SubscriptionManager.cpp
Labels: Bugs, f/subscription

#373 ssd:// protocol support (#372)
  src/core/connection/SSDConverter.hpp
Labels: DiscussionNeeded, NewFeature, f/parser
